# Generated by Django 4.2.2 on 2023-06-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=3)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
    ]
