# Generated by Django 4.2.2 on 2023-06-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacaodolar',
            old_name='valor',
            new_name='cotacao',
        ),
    ]
